import type { Experience } from "./types"

export const EXPERIENCES: Experience[] = [
	{
		company: "닥프렌즈 / 인사이트플러스",
		period: "2021.10 — 2025.05",
		role: "Frontend Developer",
		tasks: [
			"닥톡 의사 전용 사이트 및 전체 관리자 사이트 유지보수",
			"AI메신저·기관용 문자발송 서비스 개발 및 유지보수",
			"인싸이트 플러스 B2B·어드민 사이트 구축 및 유지보수",
			"Vue2→Vue3 점진 전환, TypeScript 도입, CI/CD(GitHub Actions→S3/CloudFront) 구축",
		],
		projects: [
			{
				name: "닥톡 예약연동",
				period: "2024.08 — 2025.05",
				client: "닥프렌즈",
				tech: ["Vue.js 2·3", "Nuxt.js", "TypeScript", "Pinia", "Vite", "AWS S3·CloudFront"],
				url: "https://web.doctalk.co.kr/",
				logo: "https://web.doctalk.co.kr/favicon.ico",
				description: "네이버·당근·카카오·EMR 외부 플랫폼과 환자 데이터를 연동하는 의료기관 예약 플랫폼",
				highlights: [
					"플랫폼별 API 응답을 ViewModel로 통합, 신규 연동 수정 범위를 ViewModel 내부로 한정",
					"Nuxt SSR + useSeo 모듈화로 주요 플로우 메타/OG 표준화",
					"GitHub Actions → S3/CloudFront FE 단독 배포 파이프라인 구축",
					"전문가 가입자 1,000 → 1,500 증가",
				],
			},
			{
				name: "닥톡 전문가 사이트 v5 리뉴얼",
				period: "2022.10 — 2025.05",
				client: "닥프렌즈",
				tech: ["jQuery → Vue3", "TypeScript", "Vite", "socket.io"],
				url: "https://web.doctalk.co.kr/",
				logo: "https://web.doctalk.co.kr/favicon.ico",
				description: "레거시(jQuery) 기반 전문가 플랫폼을 점진 전환으로 재구축",
				highlights: [
					"페이지 로딩 4.0s → 2.0s 개선 (Lighthouse/GSC 측정 기반)",
					"체류시간 +20%, 활동량 +25% 개선",
					"전문가 가입자 800 → 1,000 증가",
					"공통 UI·폼 검증 표준화로 화면별 구현 편차 축소",
				],
			},
			{
				name: "인사이트플러스 B2B",
				period: "2023.04 — 2024.12",
				client: "인사이트플러스",
				tech: ["Vue3", "TypeScript", "Vite", "FullCalendar"],
				description: "B2B 심리상담센터 예약·일정·상담 프로세스를 캘린더 중심으로 통합한 관리 플랫폼",
				highlights: [
					"모듈 경계 정의로 기능 확장 시 변경 범위를 특정 모듈로 한정",
					"FullCalendar 드래그/리사이즈/충돌 처리 규칙 표준화",
					"화면/도메인 상태 분리로 사이드이펙트 감소",
				],
			},
			{
				name: "Walden MVP",
				period: "2024.05 — 2024.12",
				client: "닥프렌즈",
				tech: ["React", "TypeScript", "Redux", "Vite", "AWS S3·CloudFront"],
				description: "심리상담사 대상 교육·커뮤니티·결제 MVP 구축",
				highlights: [
					"고객 인터뷰 50여 건으로 MVP 우선순위 정리 후 커뮤니티·결제 포함 베타 출시",
					"비동기 상태(loading/error/empty/success) 패턴 공통화",
					"Toss Payments 결제 플로우 상태 전이 정의 및 예외 처리",
				],
			},
			{
				name: "닥톡 AI마케터 (LMS) 자동문자발송",
				period: "2022.03 — 2022.04",
				client: "닥프렌즈",
				tech: ["Nuxt.js 2.0", "TypeScript", "SCSS"],
				url: "https://message.doctalk.co.kr/login-page",
				logo: "https://web.doctalk.co.kr/favicon.ico",
				description: "환자 맞춤형 자동 문자 발송 서비스 (사내 첫 Nuxt.js 프로젝트)",
				highlights: [
					"예약문자·직접문자·페이지네이션 중심 서비스 구축",
				],
			},
			{
				name: "닥톡 기관용 문자발송 서비스",
				period: "2022.12 — 2023.12",
				client: "닥프렌즈",
				tech: ["Vue.js 2", "TypeScript", "Vuex", "AWS S3·CloudFront"],
				url: "https://skma.doctalk.co.kr/",
				logo: "https://web.doctalk.co.kr/favicon.ico",
				description: "병원 재방문 안내 자동화를 위한 EMR 기반 문자 리텐션 서비스",
				highlights: [
					"발송 조건/주기/대상 관리 UI 구현으로 수동 작업을 설정 기반으로 전환",
					"발송 성공/실패/재시도/중복 방지를 상태·규칙으로 모델링",
				],
			},
			{
				name: "인싸이트 플러스 Admin 구축",
				period: "2023.08.07 — 2023.08.16",
				client: "인사이트플러스",
				tech: ["Vue3", "JavaScript", "Bootstrap"],
				description: "인싸이트 플러스 내부 관리자 사이트 초기 구축",
			},
		],
	},
	{
		company: "피터패트 / 이비즈빌",
		companyUrl: "http://www.pitapat.net/",
		period: "2018.05 — 2021.05",
		role: "대리 · Web Developer",
		tasks: [
			"관리 사이트의 웹접근성, 웹표준과 웹 호환성 확인 및 관리",
			"다수의 사이트 유지보수 및 관리, 백엔드 개발자와의 협업",
			"여러 업체의 이벤트 페이지 제작 및 대기업 상주·파견 업무 진행",
		],
		projects: [
			{
				name: "위닉스 제품 PD 제작",
				period: "2018.07 — 2018.10",
				client: "위닉스 · 코너크리에이티브",
				tech: ["HTML/CSS", "JavaScript", "jQuery"],
				url: "https://www.winix.com/kr/order/product.html?p_code=3577299288",
			},
			{
				name: "LG Z:IN / Hausys Global 운영",
				period: "2018.06 — 2019.04",
				client: "콜레오 · LG Z:IN",
				tech: ["HTML/CSS", "jQuery", "Ajax"],
				url: "http://www.lghausys.co.kr/zin/index.jsp",
			},
			{
				name: "LG Z:IN · 하우시스 · Z:IN mall GNB 통합",
				period: "2018.06 — 2019.04",
				client: "콜레오 · LG Z:IN",
				tech: ["HTML/CSS", "크로스브라우징"],
				url: "http://www.lxhausys.co.kr/",
			},
			{
				name: "신한 FAN 이벤트 페이지",
				period: "2018.10 — 2020.03",
				client: "신한 · 자이언트블랙",
				tech: ["JavaScript", "Ajax", "하이브리드 웹"],
			},
			{
				name: "베비언스 카브리타 이벤트 페이지",
				period: "2019.04 — 2020.07",
				client: "어쿠스틱에이",
				tech: ["Vue.js", "HTML/CSS"],
				url: "https://www.kabrita.kr/",
			},
			{
				name: "LG 화학 블로그 케미토피아",
				period: "2019.06 — 2021.05",
				client: "콜레오 · LG화학",
				tech: ["Express", "jQuery"],
				url: "https://blog.lgchem.com/",
			},
			{
				name: "삼성바이오로직스 이벤트 참여 페이지",
				period: "2020.06 — 2021.03",
				client: "삼성바이오로직스",
				tech: ["turn.js", "Ajax", "JAVA"],
				url: "http://smcdo.mywebplus.co.kr/",
			},
			{
				name: "Haevichi 호텔 유지보수",
				period: "2020.03 — 2020.08",
				client: "해비치",
				tech: ["Git cherry-pick", "Ajax", "JAVA"],
				url: "https://www.haevichi.com/",
			},
			{
				name: "삼성 갤럭시 why 국가베리 상주",
				period: "2020.10 — 2020.11",
				client: "제일펑타이",
				tech: ["HTML/CSS", "JavaScript"],
				url: "https://www.samsung.com/sec/mobile/why-galaxy/",
			},
			{
				name: "자이언트블랙 포트폴리오",
				period: "2020.03 — 2020.06",
				client: "자이언트블랙",
				tech: ["Fullpage.js", "반응형"],
				url: "http://www.giantblack.co.kr/",
			},
			{
				name: "세종텔레콤 사이트 리뉴얼",
				period: "2021.03 — 2021.05",
				client: "세종텔레콤 · 자이언트블랙",
				tech: ["반응형", "HTML/CSS"],
				url: "https://www.sejongtelecom.net/",
			},
			{
				name: "GS자이 어드민 페이지 상주",
				period: "2021.01 — 2021.05",
				client: "GS자이",
				tech: ["Bootstrap", "Zeplin", "jQuery"],
			},
		],
	},
]
